# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tests/test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tests/test.proto',
  package='prototest',
  serialized_pb=_b('\n\x10tests/test.proto\x12\tprototest\"\xf7\x02\n\nExhaustive\x12\t\n\x01\x62\x18\x01 \x02(\x08\x12\n\n\x02\x62y\x18\x02 \x02(\x0c\x12\t\n\x01\x64\x18\x03 \x02(\x01\x12%\n\x01\x65\x18\x04 \x02(\x0e\x32\x1a.prototest.Exhaustive.Enum\x12\x0b\n\x03i32\x18\x05 \x02(\x05\x12\x0b\n\x03i64\x18\x06 \x02(\x03\x12\x0b\n\x03\x66\x33\x32\x18\x07 \x02(\x07\x12\x0b\n\x03\x66\x36\x34\x18\x08 \x02(\x06\x12\t\n\x01\x66\x18\t \x02(\x02\x12,\n\x06nested\x18\n \x02(\x0b\x32\x1c.prototest.Exhaustive.Nested\x12\t\n\x01s\x18\x0b \x02(\t\x12\x0b\n\x03u32\x18\x0c \x02(\r\x12\x0b\n\x03u64\x18\r \x02(\x04\x12\x0c\n\x04tags\x18\x0e \x03(\t\x12+\n\x05nests\x18\x0f \x03(\x0b\x32\x1c.prototest.Exhaustive.Nested\x1a\x16\n\x06Nested\x12\x0c\n\x04nest\x18\x01 \x02(\t\"4\n\x04\x45num\x12\t\n\x05\x46irst\x10\x00\x12\n\n\x06Second\x10\x01\x12\t\n\x05Third\x10\x03\x12\n\n\x06\x46ourth\x10\x04*\x05\x08o\x10\xd4\x01:%\n\x06number\x12\x15.prototest.Exhaustive\x18o \x01(\x04:#\n\x04name\x12\x15.prototest.Exhaustive\x18p \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


NUMBER_FIELD_NUMBER = 111
number = _descriptor.FieldDescriptor(
  name='number', full_name='prototest.number', index=0,
  number=111, type=4, cpp_type=4, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
NAME_FIELD_NUMBER = 112
name = _descriptor.FieldDescriptor(
  name='name', full_name='prototest.name', index=1,
  number=112, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)

_EXHAUSTIVE_ENUM = _descriptor.EnumDescriptor(
  name='Enum',
  full_name='prototest.Exhaustive.Enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='First', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Second', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Third', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Fourth', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=348,
  serialized_end=400,
)
_sym_db.RegisterEnumDescriptor(_EXHAUSTIVE_ENUM)


_EXHAUSTIVE_NESTED = _descriptor.Descriptor(
  name='Nested',
  full_name='prototest.Exhaustive.Nested',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nest', full_name='prototest.Exhaustive.Nested.nest', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=346,
)

_EXHAUSTIVE = _descriptor.Descriptor(
  name='Exhaustive',
  full_name='prototest.Exhaustive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='b', full_name='prototest.Exhaustive.b', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='by', full_name='prototest.Exhaustive.by', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='d', full_name='prototest.Exhaustive.d', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='e', full_name='prototest.Exhaustive.e', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='i32', full_name='prototest.Exhaustive.i32', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='i64', full_name='prototest.Exhaustive.i64', index=5,
      number=6, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f32', full_name='prototest.Exhaustive.f32', index=6,
      number=7, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f64', full_name='prototest.Exhaustive.f64', index=7,
      number=8, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f', full_name='prototest.Exhaustive.f', index=8,
      number=9, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nested', full_name='prototest.Exhaustive.nested', index=9,
      number=10, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='s', full_name='prototest.Exhaustive.s', index=10,
      number=11, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u32', full_name='prototest.Exhaustive.u32', index=11,
      number=12, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u64', full_name='prototest.Exhaustive.u64', index=12,
      number=13, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tags', full_name='prototest.Exhaustive.tags', index=13,
      number=14, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nests', full_name='prototest.Exhaustive.nests', index=14,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_EXHAUSTIVE_NESTED, ],
  enum_types=[
    _EXHAUSTIVE_ENUM,
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(111, 212), ],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=407,
)

_EXHAUSTIVE_NESTED.containing_type = _EXHAUSTIVE
_EXHAUSTIVE.fields_by_name['e'].enum_type = _EXHAUSTIVE_ENUM
_EXHAUSTIVE.fields_by_name['nested'].message_type = _EXHAUSTIVE_NESTED
_EXHAUSTIVE.fields_by_name['nests'].message_type = _EXHAUSTIVE_NESTED
_EXHAUSTIVE_ENUM.containing_type = _EXHAUSTIVE
DESCRIPTOR.message_types_by_name['Exhaustive'] = _EXHAUSTIVE
DESCRIPTOR.extensions_by_name['number'] = number
DESCRIPTOR.extensions_by_name['name'] = name

Exhaustive = _reflection.GeneratedProtocolMessageType('Exhaustive', (_message.Message,), dict(

  Nested = _reflection.GeneratedProtocolMessageType('Nested', (_message.Message,), dict(
    DESCRIPTOR = _EXHAUSTIVE_NESTED,
    __module__ = 'tests.test_pb2'
    # @@protoc_insertion_point(class_scope:prototest.Exhaustive.Nested)
    ))
  ,
  DESCRIPTOR = _EXHAUSTIVE,
  __module__ = 'tests.test_pb2'
  # @@protoc_insertion_point(class_scope:prototest.Exhaustive)
  ))
_sym_db.RegisterMessage(Exhaustive)
_sym_db.RegisterMessage(Exhaustive.Nested)

Exhaustive.RegisterExtension(number)
Exhaustive.RegisterExtension(name)

# @@protoc_insertion_point(module_scope)
