#!/bin/bash -xe

# update apt
sudo apt-get update

# Install GIT as a base pre-requisite
sudo apt-get install -qy git curl
sudo apt-get install -qy libcurl4-openssl-dev  # curl-config for pycurl

# Install Python 2.7 as a base pre-requisite
sudo apt-get install -qy python2.7

# Install all the basic tools needed for any building and/or testing
# G++
sudo apt-get install -qy g++

# iptables
sudo apt-get install --no-install-recommends -y bridge-utils vlan

# python and ruby for generating packages
sudo apt-get install --no-install-recommends -qy debhelper autotools-dev python-unittest2 python-all-dev ruby-ronn
sudo apt-get install -qy ruby1.9.1-dev ruby1.9.1-full rpm && sudo gem install fpm

# python SSH library (paramiko) dependencies on SSL
sudo apt-get install --no-install-recommends -y libssl-dev libffi-dev

# Install python dependencies
sudo apt-get install -qy python-pip python-setuptools python-virtualenv python-neutronclient

# Update Docker to the latest version
wget -qO- https://get.docker.com/gpg | sudo apt-key add -
wget -qO- https://get.docker.com/ | sh
sudo usermod -aG docker $(whoami)

# For sandbox and mdts to work, you need to load some kernel modules
# They can be placed in /etc/modules to make sure they're loaded at boot time
sudo modprobe 8021q
sudo modprobe openvswitch
