# -*- mode: ruby -*-
# vi: set ft=ruby :

# Copyright 2014 Midokura SARL
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

API_VERSION="2"

Vagrant.configure(API_VERSION) do |config|

  vmname = "midolman-box-%s" % Time.now.strftime("%Y%b%d-%Hh%Mm")

  # base vm configuration
  config.vm.hostname  = vmname
  config.vm.box       = "precise64"
  config.vm.box_url   = "http://files.vagrantup.com/precise64.box"
  config.vm.provider "virtualbox" do |vb|
    vb.name = vmname
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--memory", "2048"]

    # according to your host settings, you may have to turn on this dns option
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  # port forwarding
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.network :forwarded_port, guest: 4000, host: 4000

  # host folder sharing
  config.vm.synced_folder "~/.m2",              "/home/vagrant/.m2"
  config.vm.synced_folder "../",                "/midonet"

  # If you need to install midolman packages inside the vm, these two lines have
  # to be commented out, otherwise apt-get will complain about existing files.
  config.vm.synced_folder "../midolman/conf",   "/etc/midolman"
  config.vm.synced_folder "../midolman/target", "/usr/share/midolman"

  # Uncomment and edit the path if you want to run the perf tests inside the vm.
  # The host path is supposed to point to a clone of the qa repository
  # config.vm.synced_folder "../../qa", "/home/vagrant/qa"

  config.vm.provision :shell do |s| s.path = 'vagrant_init.sh' end

  config.ssh.forward_agent = true

end
