/*
 * Copyright (c) 2014 Midokura SARL, All Rights Reserved.
 */
package org.midonet.odp.flows;

/** Tag interface for FlowKey and FlowAction that cannot be generated from
 *  randomly generated ByteBuffers with deserializeFrom(). */
public interface Randomize {

    /** Simulates the effects of deserializeFrom() on FlowKey and FlowAction
     *  subclasses tagged by this interface. */
    void randomize();
}
