#!/usr/bin/env bash

# Copyright 2015 Midokura SARL
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# If you want to override these variables, create a file called 'localrc'
# and place it in the same directory as this file.

# rc file(s) location
RC_DIR=$(cd $(dirname "${BASH_SOURCE:-$0}") && pwd)

# allow local overrides of env variables
if [[ -f $RC_DIR/localrc ]]; then
    source $RC_DIR/localrc
fi

# IP address/hostname to use for the services
SERVICE_HOST=${SERVICE_HOST:-127.0.0.1}

# Skip logging setup by setting this to False.  This is useful if you are
# running mido.sh as part of anther script and the logging has already been
# configured
CONFIGURE_LOGGING=${CONFIGURE_LOGGING:-True}

# Directory where all the service files will live
SERVICE_DIR=${SERVICE_DIR:-$DEVMIDO_DIR/status}

USE_SCREEN=${USE_SCREEN:-True}

# ZK Hosts (comma delimited)
ZOOKEEPER_HOSTS=${ZOOKEEPER_HOSTS:-127.0.0.1:2181}

# Flag to indicate which data store to use.
# True: Zoom-based schema
# False: Legacy ZK schema
# This flag makes possible the scenario where you want to run MidoNet API
# service that uses the ZOOM backend.
USE_NEW_STACK=${USE_NEW_STACK:-False}


# MidoNet Agent
# -------------

# Midolman configuration file location
AGENT_CONF_DIR=${AGENT_CONF_DIR:-/etc/midolman}


# MidoNet API
# -----------

ENABLE_API=${ENABLE_API:-True}

# MidoNet API port and the derived URI
API_PORT=${API_PORT:-8081}

# Time (in sec) to wait for the API to start
API_TIMEOUT=${API_TIMEOUT:-120}

# MidoNet Cluster
# ---------------

ENABLE_CLUSTER=${ENABLE_CLUSTER:-True}

# REST API port served by the cluster
CLUSTER_API_PORT=${CLUSTER_API_PORT:-8082}

# DB connection string for the tasks importer
MIDO_DB_USER=${MIDO_DB_USER:-root}
MIDO_DB_PASSWORD=${MIDO_DB_PASSWORD:-$MIDO_PASSWORD}
ENABLE_TASKS_IMPORTER=${ENABLE_TASKS_IMPORTER:-True}
TASKS_DB_CONN=${TASKS_DB_CONN:-jdbc:mysql://localhost:3306/neutron?user=$MIDO_DB_USER&password=$MIDO_DB_PASSWORD}
TASKS_DB_DRIVER_CLASS=${TASKS_DB_DRIVER_CLASS:-org.mariadb.jdbc.Driver}

# Cluster Topology API
TOPOLOGY_API_PORT=${TOPOLOGY_API_PORT:-8088}

# MidoNet Client
# --------------

# Set the API URI based on whether you are using the cluster service or not
if [[ "$USE_NEW_STACK" == "True" ]]; then
    API_URI=http://$SERVICE_HOST:$CLUSTER_API_PORT/midonet-api
else
    API_URI=http://$SERVICE_HOST:$API_PORT/midonet-api
fi

# Auth variables. They are exported so that you could source this file and
# run midonet-cli using these credentials
export MIDO_API_URL=$API_URI
export MIDO_USER=${MIDO_USER:-admin}
export MIDO_PROJECT_ID=${MIDO_PROJECT_ID:-admin}
export MIDO_PASSWORD=${MIDO_PASSWORD:-midonet}
