#!/bin/sh

NAME="midolman"
GROUP="midokura"
USER="midolman"
DATADIR=/var/lib/midolman
REMOTE_OPTION='--remote ptcp:12344'
OPTIONS_FILE=/etc/default/openvswitch-switch

# shamelessly copied from debian mysql-server package...
if ! getent group $GROUP >/dev/null ; then
        # Adding system group
        addgroup --system $GROUP >/dev/null
fi

# creating midonet user if it isn't already there
if ! getent passwd $USER >/dev/null ; then
        # Adding system user
        adduser \
          --system \
          --disabled-login \
          --ingroup $GROUP \
          --home $DATADIR \
          --gecos "MidoNet" \
          --shell /bin/false \
          $USER  >/dev/null
fi

install -d -o $USER -g $GROUP /var/log/$NAME $DATADIR

# allow group access to /var/run/quagga
usermod -G quagga $USER
chmod g+w /var/run/quagga

# enable OVSDB TCP interface on port 12344 if not already enabled
if ! grep -F -- "$REMOTE_OPTION" $OPTIONS_FILE > /dev/null; then
    echo 'OVSDB_SERVER_OPTS="$OVSDB_SERVER_OPTS' $REMOTE_OPTION\" >> $OPTIONS_FILE
fi
