#! /bin/sh

# Copyright 2014 Midokura SARL
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

. ../mmmrc

if test x"$ZOOKEEPER_STANDALONE" = xyes; then
    sed "s/\(127.0.0.1:2181\|10.0.0.2:2181,10.0.0.3:2181,10.0.0.4:2181\)/10.0.0.2:2181/" \
        -i /usr/share/midonet-api/WEB-INF/web.xml
else
    sed "s/\(127.0.0.1:2181\|10.0.0.2:2181[^<]*\)/10.0.0.2:2181,10.0.0.3:2181,10.0.0.4:2181/" \
        -i /usr/share/midonet-api/WEB-INF/web.xml
fi

if ! grep -q "zookeeper-curator_enabled" /usr/share/midonet-api/WEB-INF/web.xml; then
    sed "s/<param-name>zookeeper-zookeeper_hosts<\/param-name>/<param-name>zookeeper-curator_enabled<\/param-name>\n    <param-value>true<\/param-value>\n  <\/context-param>\n  <context-param>\n    <param-name>zookeeper-zookeeper_hosts<\/param-name>/" \
        -i /usr/share/midonet-api/WEB-INF/web.xml
fi

sed -i 's/org.midonet.api.auth.keystone.v2_0.KeystoneService/org.midonet.api.auth.MockAuthService/g' /usr/share/midonet-api/WEB-INF/web.xml

# Enable vxlan gw
awk '/midobrain-vxgw_enabled/{vxgw_section++};{if(vxgw_section && $0 !~ /.*vxgw.*/){print "    <param-value>true</param-value>"; vxgw_section=0 ; } else{ print}}' /usr/share/midonet-api/WEB-INF/web.xml > /tmp/web.xml.$$
mv /tmp/web.xml.$$ /usr/share/midonet-api/WEB-INF/web.xml

# Copy the configuration file template for Tomcat7
sudo cp ../../../../midonet-api/conf/midonet-api.xml \
    /etc/tomcat7/Catalina/localhost/midonet-api.xml

# Add a workaround for tomcat7 to start slowly: MN-2723
if ! grep -q 'java.security.egd' /etc/default/tomcat7; then
  echo 'JAVA_OPTS="$JAVA_OPTS -Djava.security.egd=file:/dev/./urandom"' >> /etc/default/tomcat7
fi
