#! /bin/bash


(cd midonet-api && bash -xe init)
(cd midonet-cp && bash -xe init)
(cd zookeeper && bash -xe init)
(cd cassandra && bash -xe init)
(cd midolman && bash -xe init)
(cd quagga && bash -xe init)
