#!/bin/bash

# Copyright 2015 Midokura SARL
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The first existing directory is used for JAVA_HOME if needed.
LIB_PATTERNS='{lib64,lib}'
JVM_SEARCH_DIRS=$( eval echo \
                 /usr/$LIB_PATTERNS/jvm/java-1.8.0-openjdk-amd64 \
                 /usr/$LIB_PATTERNS/jvm/java-8-openjdk-amd64 \
                 /usr/$LIB_PATTERNS/jvm/java-8-oracle \
                 /usr/$LIB_PATTERNS/jvm/zulu-8-amd64 \
                 /usr/$LIB_PATTERNS/jvm/jre-1.8.0-openjdk \
                 /usr/$LIB_PATTERNS/jvm/jre-8-oracle-x64 \
                 /usr/$LIB_PATTERNS/jvm/jdk-8-oracle-x64)

# zulu prints "openjdk version" while openjdk and oracle print "java version"
check_for_java8() {
    [ "x" = "x$1" ] && return 1
    [ -x "$1" ] || return 1
    $1 -version 2>&1 | grep -q 'version "1.8'
}

if [ -n "`which java`" ]; then
        java=`which java`
        # Dereference symlink(s)
        while true; do
            if [ -h "$java" ]; then
                java=`readlink -f "$java"`
                continue
            fi
            break
        done
        CUR_JAVA_DIR=$(dirname $java | sed 's!\(/jre\)*/bin!!')
        JVM_SEARCH_DIRS="$CUR_JAVA_DIR $JVM_SEARCH_DIRS"
fi
if [ ! -z "$JAVA_HOME" ]; then
    JVM_SEARCH_DIRS="$JAVA_HOME $JVM_SEARCH_DIRS"
fi

oldopts=$-
set +e
JAVA_HOME=
for jdir in $JVM_SEARCH_DIRS; do
    check_for_java8 "$jdir/bin/java"
    if [ $? -eq 0 ]; then
        JAVA_HOME="$jdir"
        break
    fi
done
echo $oldopts | grep 'e' 2>&1 >/dev/null && set -e

if [ -z "$JAVA_HOME" ] ; then
    echo "No suitable JVM found (at least v1.8.0 required)"
    exit 1
fi

JAVA="$JAVA_HOME/bin/java"

# param: exact process name
function midonet_kill_process {
    SIGNAL=
    TRY=0
    while pkill $SIGNAL -f $1
    do
        echo "$0: Sent termination signal to running node"
        TRY=$((TRY+1))
        test $TRY -eq 3 && SIGNAL='-9'
        test $TRY -eq 5 && break
        sleep 1
    done
}

# param: port number to check
function midonet_check_tcp_port {
    JMX_PORT_USER=$(netstat -nlp | awk "/^tcp.*:$1[ \t]/  {print \$NF}")
    if [ -n  "$JMX_PORT_USER" ]; then
        echo "WARNING: JMX port $1 is used by: $JMX_PORT_USER \
start will probably fail"
    fi
}
