/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.midokura.midonet.services.privsep;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * Define an enum to show an interface type
 */
public enum InterfaceType implements org.apache.thrift.TEnum {
  TUN(1),
  TAP(2);

  private final int value;

  private InterfaceType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static InterfaceType findByValue(int value) { 
    switch (value) {
      case 1:
        return TUN;
      case 2:
        return TAP;
      default:
        return null;
    }
  }
}
